type Recipe {
  id: ID!
  title: String!
  description: String
  ingredients: [Ingredient!]!
  instructions: [Instructions!]!
}

type Ingredient {
  id: ID!
  name: String!
  type: String!
  quantity: Int!
  recipe: Recipe!
}

type Instruction {
  id: ID!
  step: Int!
  direction: String!
}

type Query {
  recipe(id: ID!): Recipe!
  recipes: [Recipe!]!
}

type Mutation {
  createRecipe(name: String!, description: String!, ingredients: [Ingredient!]!, instructions: [Instruction!]!): Recipe!
  updateRecipe(id: ID!, name: String!, description: String!, ingredients: [Ingredient!]!, instructions: [Instruction!]!): Recipe!
  deleteRecipe(id: ID!): ID!
}
